server:
  port: 8357
  servlet:
    context-path: /auth

auth:
  jwt:
    pubKeyPath: F:\\keys\\rsa.pub # 公钥地址
    priKeyPath: F:\\keys\\rsa.pri # 私钥地址
    secret: sf3423jsdf#3$@FDS32
    expire: 180 # 过期时间,单位分钟
    cookieName: AUTH_TOKEN
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: auth
